In [7]:

import pandas as pd
import numpy as np

# Generar una matriz de 15x4 de números aleatorios entre 0 y 4
matrix111 = np.random.randint(1,5, size=(60, 4))

# pd.set_option('display.max_rows', None)
# pd.reset_option('display.max_rows')
matriz1222 = pd.DataFrame(matrix111, columns=['colores_hoja', 'colores_fruto', 'tallos', 'tamanios_fruto'])
print(matriz1222)

    colores_hoja  colores_fruto  tallos  tamanios_fruto
0              1              2       3               4
1              1              1       2               2
2              2              2       1               1
3              4              4       1               2
4              1              1       3               3
5              2              4       4               3
6              2              3       1               1
7              1              4       1               4
8              1              2       4               3
9              1              4       2               1
10             3              3       4               4
11             3              1       2               1
12             4              1       4               1
13             3              1       4               4
14             1              1       1               3
15             4              2       4               2
16             1              3       3               1
17             1              4       4               4
18             4              3       4               1
19             1              4       3               1
20             4              1       4               3
21             3              3       2               4
22             2              4       1               1
23             4              4       2               1
24             1              2       3               1
25             3              2       3               1
26             2              3       2               2
27             4              2       2               2
28             3              2       4               1
29             3              4       1               4
30             3              2       4               4
31             2              4       4               1
32             3              4       3               2
33             1              2       1               1
34             2              1       4               1
35             3              1       1               1
36             2              3       1               3
37             2              1       4               3
38             2              3       2               3
39             4              4       3               3
40             1              1       4               1
41             4              4       3               1
42             2              3       2               1
43             2              3       3               1
44             3              3       3               1
45             3              2       4               2
46             3              1       3               3
47             3              3       2               3
48             2              4       3               1
49             1              2       3               3
50             3              3       3               1
51             3              4       3               2
52             2              2       4               2
53             1              4       2               2
54             3              1       2               1
55             4              4       2               3
56             4              3       1               2
57             1              4       1               1
58             3              4       2               4
59             1              1       1               1

In [3]:
a = [1,2,3]

In [8]:
for i in range (1,len(a)+1):
    print(i)

1
2
3